### PR TITLE
Focus inputs

### PR DESCRIPTION
**Pull request by KorinaGraber**
Added the ability to focus textboxes, typeaheads, spinners, and datetimes. These are needed for the new importer. 

Paired with Jeff on the implementation.

Also updated waitOn in the autosave action service and busy component to use generic typing. If you pass an observable through waitOn and then subscribe to the result, it should have the same typings as before, rather than reverting to `any`

### CODE REVIEW

**Comment by arknotts** [comment]
:shipit:

**Comment by arknotts** [comment]
:shipit:

**Comment by arknotts** [comment]
:shipit:

**Comment by jtest15** [comment]
Used in this YT issue: https://renovo.myjetbrains.com/youtrack/issue/RLv2-1837

**Pull request merged**
