### PR TITLE
Styling updates

### PR DESCRIPTION
**Pull request by KorinaGraber**
Tweaks to component styling to match theme updates. Brent is still working on the field validation styling a little bit, but this should get the html a little closer to what it needs to be. 

Fixed multi-step errors and validation groups.

### CODE REVIEW

**Comment by SonofNun15** [comment]
This whole PR is very specific to a proprietary style sheet. We need to revisit and consider how these changes may affect the components in general for other use cases and other styling.

**Comment by SonofNun15** [comment]
What direction are we going with this PR?

**Comment by KorinaGraber** [comment]
Needs some design/discussion with Brent

**Comment by SonofNun15** [comment]
I guess if we want to add default styling for the busy component we can add that in the next PR.

**Pull request merged**
