### PR TITLE
Going to Lodash 4

### PR DESCRIPTION
**Pull request by SonofNun15**
**Requires**: https://github.com/RenovoSolutions/TypeScript-Angular-Utilities/pull/81

### CODE REVIEW

**Comment by SFarageNIS** [comment]
as far as I can tell... :shipit: this will help other RL21 projects successfully build.

**Comment by SonofNun15** [comment]
Test failure, unrelated. Trying to resolve.

**Comment by SonofNun15** [comment]
Wow. Actually IS lodash related. This is a bit scary.

**Comment by SonofNun15** [comment]
@SFarageNIS: More lodash fixes.

**Comment by SFarageNIS** [comment]
Some nice catches.

**Comment by SFarageNIS** [comment]
@SonofNun15 - did you happen to checkout https://github.com/lodash/lodash-migrate

**Pull request merged**
