### PR TITLE
Ng module spike

### PR DESCRIPTION
**Pull request by BrentWMiller**
**Youtrack issue: https://renovo.myjetbrains.com/youtrack/issue/IDEAS-65**
**Paired with @TheOriginalJosh**

This just touches the button components right now.

 This will eventually help with AoT and tree-shaking.

### CODE REVIEW

**Comment by BrentWMiller** [comment]
Tests don't currently run: `Disconnected (1 times), because no message in 10000 ms.`

**Comment by KorinaGraber** [comment]
I like this change. We'll have to figure out why the tests aren't running so we can get this working.

FYI, it's possible this might conflict with https://github.com/RenovoSolutions/TypeScript-Angular-Components/pull/374, although it hopefully won't

**Review by KorinaGraber — CHANGES_REQUESTED** [review]
Marking as needing changes until the tests are running. That way we don't accidentally merge it

**Comment by BrentWMiller** [comment]
Looks like it will conflict with #374, but shouldn't be too hard to fix. I think they both touch `ui.module.ts`.

**Review by KorinaGraber — APPROVED** [review]

**Comment by KorinaGraber** [comment]
Needs YT issue

**Comment by BrentWMiller** [comment]
YT issue added.

**Pull request merged**
