### PR TITLE
Remove old styling for busy spinner

### PR DESCRIPTION
**Pull request by SonofNun15**
image

### CODE REVIEW

**Comment by KorinaGraber** [comment]
We can't overwrite this or anything? The purpose of this was to provide a default style for spinners in case other consumers want to use the spinner

**Comment by SonofNun15** [comment]
Gah. Good point.

**Comment by SonofNun15** [comment]
@BrentWMiller?

**Comment by KorinaGraber** [comment]
:shipit:

**Comment by SFarageNIS** [comment]
I'm good as well. :shipit:

**Pull request merged**
