### PR TITLE
MessageLog: use strong types instead of strings

### PR DESCRIPTION
**Pull request by SonofNun15**
**Minor version change**

Requires updates to API and consumers in order to use message objects and date objects instead of strings.

### CODE REVIEW

**Comment by SonofNun15** [comment]
Do not merge until PRs are ready to update dependencies.

**Comment by KorinaGraber** [comment]
I assume there's more to come?

**Comment by KorinaGraber** [comment]
Oh wait, I guess this builds on a previous PR?

**Comment by KorinaGraber** [comment]
Ah, yes. https://github.com/RenovoSolutions/TypeScript-Angular-Components/pull/63 :shipit:

**Pull request merged**
