### PR TITLE
Documentation

### PR DESCRIPTION
**Pull request by KorinaGraber**
Added documentation for the remaining behaviors. Added documentation for link and submit buttons. I was thinking it might be nice to move common options into a 'buttons.md' file.

### CODE REVIEW

**Comment by BrentWMiller** [comment]
Yeah, it seems like most of the _button_ markdown files are similar. Could move the common options into a single file and link to it. Makes it easier to update if things change.

**Comment by KorinaGraber** [comment]
:+1: This is the new md file for buttons: https://github.com/RenovoSolutions/TypeScript-Angular-Components/pull/196/commits/dd52e60aea5d2ae470e5c73816340f45d6f629df

**Comment by SonofNun15** [comment]
Would love to see the example html pages in the bootstrapper actually contain links to the GH md files.

**Comment by KorinaGraber** [comment]
Yes, well at the moment these PRs are distinct. One touches only the md files, the other touches only the code and examples.

**Pull request merged**
