### PR TITLE
Allow message templates for message log

### PR DESCRIPTION
**Pull request by SonofNun15**
Now multiple templates can be specified on a message log with a selector to determine which template is used to display each message.

### CODE REVIEW

**Comment by SonofNun15** [comment]
Example usage:

```
<rl-message-log service="myLogService" page-size="5" selector="'type'">
    <template when-selector="mailType">
        <mail-component></mail-component>
    </template>
    <template when-selector="packageType">
        <package-component></package-component>
    </template>
</rl-message-log>
```

**Comment by KorinaGraber** [comment]
How is this going to work with the editable message log? Are you going to build your own wrapper for adding messages and attachments to the log?

**Comment by KorinaGraber** [comment]
Did you ever move the logic for selecting a generic or message log template to a shared service? Also, did angularFixture.directive() just work as-is, or did you have to make changes? Looks good overall

**Comment by SonofNun15** [comment]
Done

**Pull request merged**
