### PR TITLE
Serializable filters

### PR DESCRIPTION
**Pull request by KorinaGraber**
Updated filter group to implement the new serializable filters interface. Updated the card container to use filters as an array. We'll just use _.find to lookup filters by type. In the server-side data source, we'll convert to dictionary before serializing the filters.

**Requires utilities >= 2.7.7** https://github.com/RenovoSolutions/TypeScript-Angular-Utilities/pull/91

### CODE REVIEW

**Comment by SonofNun15** [comment]
Merge conflict

**Comment by SonofNun15** [comment]
:shipit:

**Comment by KorinaGraber** [comment]
Resolved

**Comment by SonofNun15** [comment]
Merge conflict again. I think this is pretty much effectively merged via #134...

**Comment by SonofNun15** [comment]
But GH still thinks it's open... perhaps because of the merge commit?

**Comment by KorinaGraber** [comment]
Should we merge or close? GH shows 0 changes now.

**Pull request merged**
